name: Build and Publish Docker Image

on:
  push:
    branches:
      - master 
    tags:
      - "v*.*.*"  

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: lukasmandok/docker-steamcmd-server
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # CHeckout repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Log in to GitHub Container Registry
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push Docker Image
    - name: Build and Push Docker Imag
      uses: docker/build-push-action@v4
      with:
          context: .  # Path to your Dockerfile (adjust if necessary)
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
